### ISSUE TITLE
Unable to find registered backend

### ISSUE THREAD

**Issue by maxfield-allison** [itzg/mc-router#12]
My mc-router compose.yml
```
version: '3.7'
services:
  router:
    container_name: mc-router
    image: itzg/mc-router
    ports:
      - 25565:25565
    command: --mapping=one.example.net=one:25565,two.example.net=two:25565,three.example.net=three:25565
    restart: unless-stopped
    networks:
      - t2_proxy
########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge
```

my three compose.yml

```
version: '3.7'

services:
  three:
    container_name: three
    image: itzg/minecraft-server:multiarch
    environment:
      NAME: "three- FTB Infinity Evolved"
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: "three FTB Infinity Evolved"
      ONLINE_MODE: "true"
      UID: ${PUID}
      GID: ${PGID}
      MAX_MEMORY: 12G
      MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 10
      ENABLE_QUERY: "true"
      TYPE: FTBA
      FTB_MODPACK_ID: 23
      SERVER_PORT: 25565
      QUERY_PORT: 25565
      ENABLE_RCON: "true"
      RCON_PORT: 25575
      JVM_DD_OPTS: fml.queryResult:confirm
    expose:
      - 25565
#    ports:
#      - 25566:25566
    volumes:
      - /data:/data
      - /etc/timezone:/etc/timezone:ro
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    tty: true
    stdin_open: true
    restart: unless-stopped

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge
```

and in the logs for mc-router all I see is 
```
time="2020-08-02T21:56:17Z" level=info msg="Got connection" client="10.1.0.221:65295"
time="2020-08-02T21:56:17Z" level=warning msg="Unable to find registered backend" serverAddress=three.example.net.
```

I've double and triple checked my DNS A records and SRV records and they are correct in cloudflare. No dns proxy and the SRV is pointed at the correct port and IP. My firewall isn't blocking anything on port 25565. All 3 servers are giving me the same errors when attempting to connect. The only thing that has changed is my WAN connection on the firewall and a few reboots of the host server, one of which was for a kernel update. However the issue began some time after that. After posting I will be trying to update the kernel to the latest available and if that doesn't work, I'll roll back to the mainline release and see how that fairs.
