### ISSUE TITLE
Unable to connect to backend.

### ISSUE THREAD

**Issue by Vorpal23** [itzg/mc-router#294]
Im trying to run a modded server and a vanilla server and was having a ton of issues with expositing more than one port. For some reason the connection is refused  as well as having only one port exposed is ideal. I have verified that its not a DNS issue nor a firewall issue because it was seen on both https://mcsrvstat.us/ and canyouseeme.org. with my current implantation the 'vanella' server doesn't resolve  and the modded server is refused with an error
 ```
level=warning msg="Unable to connect to backend" backend="mods:25565" client="172.22.0.1:39318" error="dial tcp 172.22.0.4:25565: connect: connection refused" serverAddress=modded.example.com
```
The docker compose yml

```
version: '3.8'

services:
    vanilla:
        container_name: vanilla
        image: itzg/minecraft-server
        environment:
            EULA: "TRUE"
            INIT_MEMORY: 2G
            MAX_MEMORY: 4G
            
        volumes:
            - ./vanilla/server:/data
            - ./vanilla/plugins:/plugins
            
        restart: unless-stopped
        tty: true
        stdin_open: true
    mods:
      container_name: mods
      image: itzg/minecraft-server:java11
      tty: true
      stdin_open: true

      environment:
        EULA: "TRUE"
        TYPE: "FORGE"
        VERSION: "1.16.5"
        FORGE_VERSION: "36.2.34"
        INIT_MEMORY: 4G
        MAX_MEMORY: 16G
      volumes:
       # attach the relative directory 'data' to the container's /data path
        - ./modded/server:/data
        - ./modded/plugins:/plugins
        - ./modded/mods:/mods
    mc-router:
        container_name: router
        image: itzg/mc-router
        depends_on:
          - vanilla
          - mods
        environment:
            API_BINDING: ":25564"
            MAPPING : |
              mc.example.com=vanilla:25565
              modded.example.com=mods:25565
        ports:
            - 25565:25565
            # bind the API port to only loopback, this avoids external exposure
            - 127.0.0.1:25564:25564

```
The Vanilla server was working until i launched a new container for the modded server that was set up identically to the mods container pointed at port 48
I have windows firewall rules allowing all traffic on 25565, 48, 50, and 25564 but im aware that 25564 isnt facing the internet.

Where do I even begin to fix this issue.
