### ISSUE TITLE
Can't get the docker compose example files to work

### ISSUE THREAD

**Issue by LTE-creator** [itzg/mc-router#341]
I've been trying to get Minecraft servers running behind a proxy for quite some time so I was really happy when i saw such a seemingly easy way to do it. However when trying it out i couldn't get any of the default/example files working.
I've tried under Debian and Macos under the latest docker and i get the same behavior each time: "unknown host" when i put the intended subdomain and connection on the default server when i use the top level domain alone (localhost instead of mc1.localhost) or unknown when the default is null.
Any ideas on how to fix this?
Thanks a ton.

**Comment by itzg** [comment]
Please show what you're actually trying and what logs you get. It's impossible to speculate otherwise since all of the examples work.

**Comment by itzg** [comment]
Also be sure to set DEBUG env var to "true" to see what proxy resolution is attempting.

**Comment by LTE-creator** [comment]
For the docker socket discovery i'm running literally the same code as in the [example](https://github.com/itzg/mc-router/blob/master/docs/sd-docker.docker-compose.yml):
```
services:
  mcfoo:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MOTD: "foo"
    volumes:
      - mcfoodata:/data
    labels:
      mc-router.host: "foo.localhost"
      mc-router.default: true
  mcbar:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MOTD: "bar"
    volumes:
      - mcbardata:/data
    labels:
      mc-router.host: "bar.localhost"
  router:
    image: itzg/mc-router:latest
    command: "-debug -in-docker"
    depends_on:
      - mcfoo
      - mcbar
    ports:
      - "25565:25565"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  mcfoodata:
  mcbardata:
``` 
(yanked from my config)
And for the example on the [readme](https://github.com/itzg/mc-router?tab=readme-ov-file#docker-compose-usage) I'm running the same code except for the *.example.com that i replaced with *.localhost:
```
services:
  vanilla:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
  forge:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FORGE
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
    depends_on:
      - forge
      - vanilla
    environment:
      MAPPING: |
        vanilla.localhost=vanilla:25565
        forge.localhost=forge:25565
    ports:
      - "25565:25565"
``` 

Like I said i really tried to go back to the basics but right now I can't even figure how to make that work...
