### ISSUE TITLE
Unable to route traffic to GTNH server on k3s

### ISSUE THREAD

**Issue by behappiness** [itzg/mc-router#378]
## Unable to route traffic through mc-router to GTNH Minecraft server on k3s

Hi! Thanks for your huge work. I have some trouble setting up my servers with k3s.

### Description
I have tried to configure the https://github.com/itzg/mc-router/blob/master/docs/k8s-autoscale.yaml file, to no avail.

### Files

**pvc.yaml**
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-gtnh-pvc
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: openebs-zfspv-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-gtnh-backups
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: openebs-zfspv-retain

```

**mc-router.yaml**
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-router
  namespace: minecraft
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: services-watcher
  namespace: minecraft
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["watch","list"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "statefulsets/scale"]
  verbs: ["watch","list","get","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mc-router-services-watcher
  namespace: minecraft
subjects:
- kind: ServiceAccount
  name: mc-router
  namespace: minecraft
roleRef:
  kind: ClusterRole
  name: services-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: mc-router
  namespace: minecraft
spec:
  type: NodePort
  externalTrafficPolicy: Local
  externalIPs:
    - 10.0.0.1
  ports:
  - targetPort: web
    name: web
    port: 8080
    nodePort: 38080
  - targetPort: proxy
    name: proxy
    port: 25565
    nodePort: 25565
  selector:
    run: mc-router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mc-router
  name: mc-router
  namespace: minecraft
spec:
  selector:
    matchLabels:
      run: mc-router
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: mc-router
    spec:
      serviceAccountName: mc-router
      containers:
      - image: aapjeisbaas/mc-router:latest
        imagePullPolicy: Always
        name: mc-router
        args: ["--api-binding", ":8080", "--in-kube-cluster","--auto-scale-up","--use-proxy-protocol","--debug"]
        env:
          - name: AUTO_SCALE_UP
            value: "true"
        ports:
        - name: proxy
          containerPort: 25565
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: 50Mi
            cpu: "100m"
          limits:
            memory: 100Mi
            cpu: "250m"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mc-shutdown
  namespace: minecraft
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets", "statefulsets/scale"]
  verbs: ["list","get","update", "patch"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mc-shutdown
  namespace: minecraft
subjects:
- kind: ServiceAccount
  name: mc-shutdown
  namespace: minecraft
roleRef:
  kind: ClusterRole
  name: mc-shutdown
  apiGroup: "rbac.authorization.k8s.io"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-shutdown
  namespace: minecraft
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mc-shutdown
  namespace: minecraft
spec:
  schedule: "0 7 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: mc-shutdown
          restartPolicy: OnFailure
          containers:
          - name: shutdown
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - source shutdown-script.sh
            volumeMounts:
                - name: shutdown-script
                  mountPath: /shutdown-script.sh
                  subPath: shutdown-script.sh
                  readOnly: true
          volumes:
          - name: shutdown-script
            configMap:
              name: shutdown-script
              items:
                - key: shutdown-script.sh
                  path: shutdown-script.sh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shutdown-script
  namespace: minecraft
data:
  shutdown-script.sh: |
    #!/bin/bash
    MC_PODS=$(kubectl get pods -l containertype=minecraft-server -o=jsonpath="{range .items[*]}{.metadata.name},"| sed 's/,/\n/g') 
    for p in $MC_PODS; do
      echo "found minecraft pod $p, sleeping 120 seconds to prevent shutdown before login"
      sleep 120
      deployment=$(echo $p |sed 's/-0//g')
      # check online player count in the mc server
      if [[ $(kubectl exec -i $p -- /usr/local/bin/mc-monitor status) == *"online=0"* ]] ;then
        kubectl scale statefulset $deployment --replicas=0
      fi
    done

```

**gtnh.yaml**
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-gtnh-deployment
  namespace: minecraft
  labels:
    app: minecraft-gtnh-container
spec:
  serviceName: minecraft-gtnh-deployment
  selector:
    matchLabels:
      app: minecraft-gtnh-container 
  replicas: 0
  template:
    metadata:
      labels:
        app: minecraft-gtnh-container
        containertype: minecraft-server
    spec:
      containers:
      - name: minecraft-gtnh-deployment
        image: itzg/minecraft-server:java21
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "16384Mi"
        env:
        - name: EULA
          value: "true"
        - name: TYPE
          value: "CUSTOM"
        - name: GENERIC_PACKS
          value: "GT_New_Horizons_2.7.2_Server_Java_17-21"
        - name: GENERIC_PACKS_SUFFIX
          value: ".zip"
        - name: GENERIC_PACKS_PREFIX
          value: "https://downloads.gtnewhorizons.com/ServerPacks/"
        - name: SKIP_GENERIC_PACK_UPDATE_CHECK
          value: "true"
        - name: "MEMORY"
          value: "12G"
        - name: MAX_MEMORY
          value: "14G"
        - name: DUMP_SERVER_PROPERTIES
          value: "TRUE"
        - name: CREATE_CONSOLE_IN_PIPE
          value: "true"
        - name: JVM_OPTS
          value: "-Dfml.readTimeout=180 @java9args.txt"
        - name: CUSTOM_JAR_EXEC
          value: "-jar lwjgl3ify-forgePatches.jar nogui"
        - name: ENABLE_WHITELIST
          value: "true"
        - name: WHITELIST
          value: "some,people"
        - name: OPS
          value: "some"
        - name: RCON_PASSWORD
          value: "verysecure"
        - name: DIFFICULTY
          value: "hard"
        - name: MAX_PLAYERS
          value: "8"
        - name: VIEW_DISTANCE
          value: "12"
        - name: SNOOPER_ENABLED
          value: "false"
        - name: MODE
          value: "survival"
        - name: MOTD
          value: "#GTNH-2.7.2"
        - name: ONLINE_MODE
          value: "true"
        - name: ALLOW_FLIGHT
          value: "true"
        - name: SERVER_NAME
          value: "GTNH"
        - name: ENABLE_COMMAND_BLOCK
          value: "true"
        - name: LEVEL_TYPE
          value: "rwg"
        - name: OP_PERMISSION_LEVEL
          value: "4"
        - name: STOP_SERVER_ANNOUNCE_DELAY
          value: "60"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
          # Give it i + p * f seconds to be ready, so 120 seconds
          initialDelaySeconds: 300
          periodSeconds: 5
          failureThreshold: 24
        # Monitor ongoing liveness
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
          initialDelaySeconds: 300
          periodSeconds: 60
        volumeMounts:
        - name: mc-data
          mountPath: /data
          
      volumes:
      - name: mc-data
        persistentVolumeClaim:
          claimName: minecraft-gtnh-pvc
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-gtnh-deployment
  namespace: minecraft
  annotations:
    "mc-router.itzg.me/externalServerName": "gtnh.example.net,10.0.0.1,public.ip"
spec:
  ports:
  - port: 25565
  selector:
    app: minecraft-gtnh-container
```

### Steps to Reproduce
1. Deploy the pvc, mc-router, gtnh configuration
3. Attempt to connect to the Minecraft server through the router

### Expected Behavior
- Autoscaling to work
- Shutdown to work
- Backup is not working (the config files don't include this, but I tried https://github.com/itzg/docker-mc-backup/tree/master kubernetes example and the image is not pulling doesn't matter what I set)
- Routing to work

### Current Behavior
- Autoscaling is working, but I get the msg "StatefulSet scale up failed at step 2": 
```log
time="2025-03-25T01:13:34Z" level=debug msg="StatefulSet scale up step 1" service=minecraft-gtnh-deployment
time="2025-03-25T01:13:34Z" level=debug msg="StatefulSet scale up step 2" service=minecraft-gtnh-deployment statefullsetname=minecraft-gtnh-deployment
time="2025-03-25T01:13:34Z" level=debug msg="StatefulSet of Service Replicas" replicas=1 service=minecraft-gtnh-deployment statefulSet=minecraft-gtnh-deployment
time="2025-03-25T01:13:34Z" level=debug msg="StatefulSet scale up failed at step 2" service=minecraft-gtnh-deployment statefullsetname=minecraft-gtnh-deployment
time="2025-03-25T01:13:34Z" level=info msg="Connecting to backend" backendHostPort="10.43.29.248:25565" client="10.0.2.2:50846" server=10.0.0.1
```
- Shutdown is working if I remember correctly
- Backup image not pulling
- Routing not working. I've somehow managed to get 1-2 replies when a player was not on the whitelist and instead of connection error, they got not on whitelist. It finds the backend, tries to connect it, but doesn't get through.

### Environment
- k3s cluster
- Minecraft server: GTNH 2.7.2 (most settings from: https://github.com/itzg/docker-minecraft-server/blob/master/examples/gtnh/docker-compose.yaml and https://gtnh.miraheze.org/wiki/Server_Setup_(Container))

### Additional logs

[mc-router.log](https://github.com/user-attachments/files/19440807/mc-router.log)

[gtnh.log](https://github.com/user-attachments/files/19440809/gtnh.log)
