### ISSUE TITLE
Unable to find registered backend

### ISSUE THREAD

**Issue by anLizard** [itzg/mc-router#9]
I get instantly disconnected upon trying to connect to a routed server.

docker-compose log after trying to connect to first.example.com:
`mc-router  | time="2020-05-08T17:58:41Z" level=warning msg="Unable to find registered backend" serverAddress=example.com.`

Minecraft client error is just "Disconnected".
I opened port 25565 and made sure the A records on my DNS exist.
I can connect to both servers if I map them to two different open ports without the router.

docker-compose.yml:
```
version: '3'

services:

  router:
    image: itzg/mc-router
    container_name: mc-router
    ports:
      - 25565:25565
    command: --mapping=first.example.com=first:25565,second.example.com=second:25565

  first:
    image: itzg/minecraft-server
    container_name: mc-first
    expose:
      - "25565"
    volumes:
      - ./first:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      EULA: "TRUE"
    restart: always

  second:
    image: itzg/minecraft-server
    container_name: mc-second
    expose:
      - "25565"
    volumes:
      - ./second:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      EULA: "TRUE"
    restart: always
```
